AWSTemplateFormatVersion: 2010-09-09
Transform: AWS::Serverless-2016-10-31

Parameters:
  WebsiteBucketName:
    Type: String
    Description: 'The S3 bucket for CodePipeline artifacts.'
  ApiStageName:
    Type: String
    Description: 'The stage name for the API gateway.'
  Domain:
    Type: String
    Description: 'The registered domain name.'
  SubDomain:
    Type: String
    Description: 'The sub-domain name for the website.'
  WebsiteBucketDNSName:
    Type: String
    Description: 'The registered domain name.'
  WebsiteBucketHostedZoneId:
    Type: String
    Description: 'The sub-domain name for the website.'

Resources:
  DNS:
    Type: AWS::Route53::RecordSet
    Properties:
      HostedZoneName: !Sub '${Domain}.'
      Name: !Sub '${SubDomain}.${Domain}.'
      Type: A
      AliasTarget:
        HostedZoneId: !Ref WebsiteBucketHostedZoneId
        DNSName: !Ref WebsiteBucketDNSName

  ApiGatewayApi:
    Type: AWS::Serverless::Api
    Properties:
      StageName: !Ref ApiStageName

  ApiFunction: # Adds a GET API endpoint at "/" to the ApiGatewayApi via an API event
    Type: AWS::Serverless::Function
    Properties:
      Events:
        ApiEvent:
          Type: Api
          Properties:
            Path: /
            Method: get
            RestApiId: !Ref ApiGatewayApi
      Runtime: python3.6
      Handler: index.handler
      InlineCode: |
        def handler(event, context):
                      print("In lambda handler")

                      resp = {
                          "statusCode": 200,
                          "headers": {
                              "Access-Control-Allow-Origin": "*",
                          },
                          "body": "This is the response from lambda function"
                      }

                      return resp

  WebsiteBucket:
    Type: AWS::S3::Bucket
    Properties:
      AccessControl: PublicRead
      BucketName: !Ref WebsiteBucketName
      MetricsConfigurations:
        - Id: EntireBucket
      WebsiteConfiguration:
        IndexDocument: index.html
        ErrorDocument: error.html
      Tags:
        - Key: StackName
          Value: !Ref AWS::StackName
    DeletionPolicy: Delete

Outputs:
  BucketEndpoint:
    Description: The DNS name for the bucket
    Value: !GetAtt WebsiteBucket.WebsiteURL
    Export:
      Name: BucketEndpoint
  WebsiteEndpoint:
    Description: The DNS name for the website
    Value: !Sub "http://${DNS}"
    Export:
      Name: WebsiteEndpoint
  ApiGatewayID:
    Description: The root resource ID for the API Gateway
    Value: !Ref ApiGatewayApi
    Export:
      Name: ApiGatewayID